# This is the control file for Travis continuous integration system.
#
# It is used automatically for the repositories on Github if it's found in the
# root directory of the project.
language: cpp

compiler:
    - clang
    - gcc

sudo: false

env:
    - wxCONFIGURE_FLAGS=""
    - wxCONFIGURE_FLAGS="-DBUILD_SHARED_LIBS=ON"

install:
    - mkdir bin
    - cd bin

script:
    - cmake $wxCONFIGURE_FLAGS .. && cmake --build .
