environment:
  matrix:
    - GENERATOR: "Visual Studio 12"
      BUILD_SHARED_LIBS: ON

    - GENERATOR: "Visual Studio 12"
      BUILD_SHARED_LIBS: OFF

    - GENERATOR: "Visual Studio 11"
      BUILD_SHARED_LIBS: ON

    - GENERATOR: "Visual Studio 11"
      BUILD_SHARED_LIBS: OFF

platform:
  - x86
  - x64

# configuration:
#   - Debug
#   - Release

build_script:
  - ps: if($env:PLATFORM -eq "x64") { $env:CMAKE_GEN_SUFFIX=" Win64" }
  - cmake "-G%GENERATOR%%CMAKE_GEN_SUFFIX%" -DBUILD_SHARED_LIBS=%BUILD_SHARED_LIBS% -DWX_USE_EXT_EXPAT=OFF -DWX_USE_EXT_JPEG=OFF -DWX_USE_EXT_PNG=OFF -DWX_USE_EXT_PNG=OFF -DWX_USE_EXT_TIFF=OFF -DWX_USE_EXT_ZIP=OFF -H. -B_builds
  - cmake --build _builds --config "%CONFIGURATION%"

on_failure:
  - ps: cat _builds/CMakeFiles/CMakeOutput.log
  - ps: cat _builds/CMakeFiles/CMakeError.log