#define wxSTC_VISUALPROLOG_STRING_VERBATIM_EOL -1
#define wxSTC_VISUALPROLOG_STRING_VERBATIM_SPECIAL -1
#define wxSTC_VISUALPROLOG_STRING_VERBATIM -1
#define wxSTC_VISUALPROLOG_STRING_EOL_OPEN -1
#define wxSTC_VISUALPROLOG_CHARACTER_ESCAPE_ERROR -1
#define wxSTC_VISUALPROLOG_CHARACTER_TOO_MANY -1
#define wxSTC_VISUALPROLOG_CHARACTER -1
#define wxSTC_CSS_MEDIA -1

