# Copyright (C) 2020 Sebastian Pipping <sebastian@pipping.org>
# Licensed under the MIT license

name: Run macOS Travis CI tasks

on:
  pull_request:
  push:
  schedule:
    - cron: '0 2 * * 5'  # Every Friday at 2am

jobs:
  checks:
    name: Perform checks
    strategy:
      matrix:
        include:
          # NOTE: This is a quick port from .travis.yml in reaction to
          #       Homebrew issues at Travis CI.  While we have the matrix
          #       in two places, please keep the two files in sync.  Thank you!
          - MODE: cmake-oos
          - MODE: distcheck
          - MODE: qa-sh
            FLAT_ENV: CC=clang CXX=clang++ LD=clang++ QA_SANITIZER=address
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - name: Install build dependencies
      run: |
        sudo rm /usr/local/bin/2to3  # so that "brew link" will work
        brew bundle                  # acts upon file Brewfile
    - name: Perform check "${{ matrix.MODE }}"
      env:
        MODE: ${{ matrix.MODE }}
        TRAVIS_OS_NAME: osx
      run: |
        env ${{ matrix.FLAT_ENV }} ./.travis.sh
