name: Push Build

on:
  push:

jobs:
  build:
    runs-on: windows-latest

    steps:
    #- name: Checkout
    #  uses: actions/checkout@v2
    
    - uses: actions/checkout@v2
    - name: Checkout submodules
      shell: bash
      run: |
        auth_header="$(git config --local --get http.https://github.com/.extraheader)"
        git submodule sync --recursive
        git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1

    - name: Setup NuGet
      uses: warrenbuckley/Setup-Nuget@v1

    - name: Setup Build Number
      uses: einaregilsson/build-number@v2
      with:
        token: ${{secrets.GITHUB_TOKEN}}
    
    - name: Setup MSVC   
      uses: ilammy/msvc-dev-cmd@v1
      with:
      #  arch: amd64
        toolset: 16.0

    - name: Read version info
      run: build\tools\msvs\getversion.bat

    - name: Build - Release
      working-directory: ./build/msw
      run: nmake -f makefile.vc BUILD=Release SHARED=1 COMPILER_VERSION=190 OFFICIAL_BUILD=1 TARGET_CPU=AMD64
      
    - name: Build - Debug
      working-directory: ./build/msw
      run: nmake -f makefile.vc BUILD=Debug SHARED=1 COMPILER_VERSION=190 OFFICIAL_BUILD=1 TARGET_CPU=AMD64

    - name: Build Push Nuget Package.
      if: github.ref == 'refs/heads/master'
      run: |
        build\tools\msvs\nugetpush.bat -OutputDirectory dist -properties repository=${{github.repository}}
        nuget push dist\*.nupkg -NoSymbols -source https://api.nuget.org/v3/index.json -apikey ${{ secrets.nuget_apikey }}
