name: Push Build

on:
  push:

jobs:
  build:
    runs-on: windows-latest

    steps:
    #- name: Checkout
    #  uses: actions/checkout@v2
    
    - uses: actions/checkout@v2
    - name: Checkout submodules
      shell: bash
      run: |
        auth_header="$(git config --local --get http.https://github.com/.extraheader)"
        git submodule sync --recursive
        git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1

    - name: Setup NuGet
      uses: warrenbuckley/Setup-Nuget@v1

    - name: Setup Build Number
      uses: einaregilsson/build-number@v2
      with:
        token: ${{secrets.GITHUB_TOKEN}}
    - name: GitHub package Registry
      run: nuget sources add -name GPR -Source https://nuget.pkg.github.com/${{ github.repository }}/index.json -Username ${{ github.actor }} -Password ${{ secrets.GITHUB_TOKEN }}
    
    - name: Setup MSVC   
      uses: ilammy/msvc-dev-cmd@v1
      with:
      #  arch: amd64
        toolset: 16.0

    - name: Read version info
      run: build\tools\msvs\getversion.bat

    - name: Build - MSVC2019 - x64 Release Dlls
      working-directory: ./build/msw
      run: |
        nmake -f makefile.vc BUILD=Release SHARED=1 COMPILER_VERSION=160 OFFICIAL_BUILD=1 TARGET_CPU=AMD64
        nuget pack -OutputDirectory dist -OutputFileNamesWithoutVersion -properties id=wxWidgets.VC160.Shared;version=%wxMAJOR_VERSION%.%wxMINOR_VERSION%.%wxRELEASE_NUMBER%.${{BUILD_NUMBER}};dllpath=lib\vc160_x64_dll;repository=${{github.repository}}
        nuget push dist\*.nupkg 

    - name: Build - MSVC2019 - x64 Debug Dlls
      working-directory: ./build/msw
      run: nmake -f makefile.vc BUILD=Debug SHARED=1 COMPILER_VERSION=160 OFFICIAL_BUILD=1 TARGET_CPU=AMD64
