name: Push Build

on:
  push:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
        submodules: recursive
        clean: true

    - name: Setup NuGet
      uses: warrenbuckley/Setup-Nuget@v1

    - name: Setup MSVC   
      uses: ilammy/msvc-dev-cmd@v1
      with:
      #  arch: amd64
        toolset: 16.0

    - name: Build - MSVC2019 - x64 Release Dlls
      working-directory: ./build/msw
      run: nmake -f makefile.vc BUILD=Release SHARED=1 COMPILER_VERSION=160 OFFICIAL_BUILD=1 TARGET_CPU=AMD64

    - name: Build Push Nuget Package.
      if: github.ref == 'refs/heads/master'
      run: |
        SET BUILD_NUMBER=${{GITHUB_RUN_NUMBER}}
        build\tools\msvs\nugetpush.bat -OutputDirectory dist -properties repository=${{github.repository}}
        nuget push dist\*.nupkg -NoSymbols -source https://api.nuget.org/v3/index.json -apikey ${{ secrets.nuget_apikey }}

    - name: Build - MSVC2019 - x64 Debug Dlls
      working-directory: ./build/msw
      run: nmake -f makefile.vc BUILD=Debug SHARED=1 COMPILER_VERSION=160 OFFICIAL_BUILD=1 TARGET_CPU=AMD64
